include ../../Rules.mk

LIBSRCS = \
		  item.cpp \
		  item_list.cpp \
		  item_manager.cpp \
		  item_ess_def.cpp \
		  item_essence.cpp \
		  itembody/item_equip.cpp \
		  itembody/item_team_npc.cpp \
		  itembody/item_task_scroll.cpp \
		  itembody/item_pet.cpp \
		  itembody/item_card.cpp \
		  itembody/item_skill.cpp \
		  itembody/item_talent.cpp \
		  itembody/item_mount.cpp


all : lib
	
include $(SOLUTION_ROOT_DIR)/shared/mk/gcc.build.lib.mk

lib : $(LIB_O)

