include ../../Rules.mk

SOLUTION_ROOT_RELATIVE_PATH = ../../..

LIBSRCS = \
		  player_move_ctrl.cpp \
		  pmv_session.cpp \
		  npc_mvsession.cpp


all : lib
	
include $(SOLUTION_ROOT_DIR)/shared/mk/gcc.build.lib.mk

lib : $(LIB_O)

