include ../../../Rules.mk

SOLUTION_ROOT_RELATIVE_PATH = ../../../..

LIBSRCS = \
		  base_datatempl.cpp \
		  templ_manager.cpp \
		  service_templ.cpp


all : lib
	
include $(SOLUTION_ROOT_DIR)/shared/mk/gcc.build.lib.mk

lib : $(LIB_O)

