include ../../Rules.mk

SOLUTION_ROOT_RELATIVE_PATH = ../../..

SUBSYS_DIR = subsys

LIBSRCS = \
		  player.cpp \
		  cmdprepare.cpp \
		  player_ctrl.cpp \
		  player_state.cpp \
		  playercmd.cpp \
		  player_sender.cpp \
		  inter_msg_filter.cpp \
		  player_msg_handler.cpp \
		  psession.cpp \
		  master_rpc.cpp \
		  player_subsys.cpp \
		  player_prop.cpp \
		  subsys_if.cpp \
		  debug_cmd.cpp \
		  task_if.cpp \
		  achieve_if.cpp \
		  filter.cpp \
		  skill_if.cpp \
		  player_value_prop.cpp \
		  $(SUBSYS_DIR)/player_inventory.cpp \
		  $(SUBSYS_DIR)/player_combat.cpp \
		  $(SUBSYS_DIR)/player_skill.cpp \
		  $(SUBSYS_DIR)/player_service.cpp \
		  $(SUBSYS_DIR)/player_team.cpp \
		  $(SUBSYS_DIR)/player_pet.cpp \
		  $(SUBSYS_DIR)/player_transfer.cpp \
		  $(SUBSYS_DIR)/player_task.cpp \
		  $(SUBSYS_DIR)/player_instance.cpp \
		  $(SUBSYS_DIR)/player_buddy.cpp \
		  $(SUBSYS_DIR)/player_buff.cpp \
		  $(SUBSYS_DIR)/player_gather.cpp \
		  $(SUBSYS_DIR)/player_drama.cpp \
		  $(SUBSYS_DIR)/player_chat.cpp \
		  $(SUBSYS_DIR)/player_mall.cpp \
		  $(SUBSYS_DIR)/player_mail.cpp \
		  $(SUBSYS_DIR)/player_map_team.cpp \
		  $(SUBSYS_DIR)/player_talent.cpp \
		  $(SUBSYS_DIR)/player_auction.cpp \
		  $(SUBSYS_DIR)/player_friend.cpp \
		  $(SUBSYS_DIR)/player_cooldown.cpp \
		  $(SUBSYS_DIR)/player_duel.cpp \
		  $(SUBSYS_DIR)/player_reputation.cpp \
		  $(SUBSYS_DIR)/player_prop_reinforce.cpp \
		  $(SUBSYS_DIR)/player_achieve.cpp \
		  $(SUBSYS_DIR)/player_enhance.cpp \
		  $(SUBSYS_DIR)/player_title.cpp \
		  $(SUBSYS_DIR)/player_star.cpp \
		  $(SUBSYS_DIR)/player_battleground.cpp \
		  $(SUBSYS_DIR)/player_card.cpp \
		  $(SUBSYS_DIR)/player_arena.cpp \
		  $(SUBSYS_DIR)/player_landmine.cpp \
		  $(SUBSYS_DIR)/player_bw_list.cpp \
		  $(SUBSYS_DIR)/player_counter.cpp \
		  $(SUBSYS_DIR)/player_punch_card.cpp \
		  $(SUBSYS_DIR)/player_gevent.cpp \
		  $(SUBSYS_DIR)/player_mount.cpp \
		  $(SUBSYS_DIR)/player_participation.cpp \
		  $(SUBSYS_DIR)/player_boss_challenge.cpp \
		  $(SUBSYS_DIR)/player_world_boss.cpp


all : lib
	
include $(SOLUTION_ROOT_DIR)/shared/mk/gcc.build.lib.mk

lib : $(LIB_O)

