include ../../../Rules.mk


SOLUTION_ROOT_RELATIVE_PATH = ../../../..

LIBSRCS = \
		  func_table.cpp \
		  area_player_leaf.cpp \
		  area_ev_manager.cpp \
		  area_btlib_link.cpp


all : lib
	
include $(SOLUTION_ROOT_DIR)/shared/mk/gcc.build.lib.mk

lib : $(LIB_O)

