include ../../../Rules.mk


SOLUTION_ROOT_RELATIVE_PATH = ../../../..

LIBSRCS = \
		  event_sys.cpp \
		  area_ev_if.cpp \
		  script_xml_op.cpp \
		  ev_lua_ent.cpp


all : lib
	
include $(SOLUTION_ROOT_DIR)/shared/mk/gcc.build.lib.mk

lib : $(LIB_O)

