include ../../../Rules.mk

SOLUTION_ROOT_RELATIVE_PATH = ../../../..

LIBSRCS = \
		  base_mapdata.cpp \
		  mapdata_manager.cpp


all : lib
	
include $(SOLUTION_ROOT_DIR)/shared/mk/gcc.build.lib.mk

lib : $(LIB_O)

