#ifndef COMMON_OBJDATAPOOL_ATTR_TYPE_DEF_H_
#define COMMON_OBJDATAPOOL_ATTR_TYPE_DEF_H_

#define OBJECT_ATTR_TYPE_LOWER_LIMIT ((int)0)
#define OBJECT_ATTR_TYPE_UPPER_LIMIT ((int)10240)

#define	PLAYER_ATTR_TYPE_LOWER_LIMIT ((int)100)                                   // 100
#define PLAYER_ATTR_TYPE_UPPER_LIMIT ((int)(PLAYER_ATTR_TYPE_LOWER_LIMIT + 1000)) // 1100

#define GLOBAL_DATA_TYPE_LOWER_LIMIT ((int)(PLAYER_ATTR_TYPE_UPPER_LIMIT + 100))  // 1200
#define GLOBAL_DATA_TYPE_UPPER_LIMIT ((int)(GLOBAL_DATA_TYPE_LOWER_LIMIT + 100))  // 1300


#endif // COMMON_OBJDATAPOOL_ATTR_TYPE_DEF_H_
